-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 18:10:50 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stock_price
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stock_price` ;

-- -----------------------------------------------------
-- Schema stock_price
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_price` DEFAULT CHARACTER SET utf8 ;
USE `stock_price` ;

-- -----------------------------------------------------
-- Table `stock_price`.`grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`grades` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`grades` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_price`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`users` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `grade_id` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fb_id` VARCHAR(45) NULL,
  `profile_img` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_grade1_idx` (`grade_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_user_grade1`
    FOREIGN KEY (`grade_id`)
    REFERENCES `stock_price`.`grades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_price`.`stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`stocks` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`stocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `srt_code` VARCHAR(45) NOT NULL,
  `issue_code` VARCHAR(45) NOT NULL,
  `kor_name` VARCHAR(45) NOT NULL,
  `kor_abbr` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `market` VARCHAR(10) NOT NULL,
  `date` DATE NOT NULL,
  `end_price` INT NOT NULL,
  `present_price` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_price`.`predictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`predictions` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`predictions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `stock_id` INT NOT NULL,
  `will_up` INT NOT NULL,
  `today_price` VARCHAR(45) NOT NULL,
  `result_price` VARCHAR(45) NULL,
  `result` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_prediction_user_idx` (`user_id` ASC),
  INDEX `fk_prediction_stock1_idx` (`stock_id` ASC),
  INDEX `idx_will_up` (`will_up` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_prediction_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `stock_price`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prediction_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock_price`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_price`.`rankings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`rankings` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`rankings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `ranking` INT NOT NULL,
  `hit_rating` DECIMAL(5,2) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ranking_user1_idx` (`user_id` ASC),
  INDEX `idx_hit_rating` (`hit_rating` ASC),
  INDEX `idx_ranking` (`ranking` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_ranking_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stock_price`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_price`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stock_price`.`keywords` ;

CREATE TABLE IF NOT EXISTS `stock_price`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyword_list` VARCHAR(500) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `stock_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_keyword_stock1_idx` (`stock_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_keyword_stock1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stock_price`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
